# Generated by Django 2.0.4 on 2018-04-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_api', '0002_auto_20180408_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillinfo',
            name='rejected',
        ),
    ]
